variables:
  BUILD_SHELL: 'yarn lowcode:build'
  OBJ_SAPCE: 'anydoor-static-cdn'
  BASE_PATH: 'lowcode'
  SKIP_FIXED_STRINGS: '.html'
  SKIP_FILE_PREFIXES: 'preview.js,index.js,preview.css,preview.js'

cache:
  paths:
    - node_modules/
    - build/

stages:
  - install
  - build
  - deploy
  - upload

install:
  stage: install
  script:
    - 'yarn install'

build:
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - $BUILD_SHELL
    - ls
pages:
  stage: deploy
  script:
    - rm -rf public/*
    - mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
upload:
   stage: upload
   script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version)")
    - export PROJECT_NAME=$(node -e "console.log(require('./package.json').name)")
    - qshell qupload2 --bucket=$OBJ_SAPCE --src-dir=public/lowcode --key-prefix=$BASE_PATH/$PROJECT_NAME@$PROJECT_VERSION/ --skip-fixed-strings=$SKIP_FIXED_STRINGS --skip-file-prefixes=$SKIP_FILE_PREFIXES
